### ISSUE TITLE
ReadMe

### ISSUE THREAD

**Issue by clairekrogers** [JoyJing1/Friendex#1]
* MVP: each feature currently has the same bullet points.  Customize these to explain what each feature does and it's purpose.  
* Remove styling as specific phases.  Style as you go along, marking a feature as complete only after it is sufficiently styled.  
* Phase 5: this shouldn't take 1.5 days.  You can probably do it in less than a day. 
* When you get to newsfeed, I recommend doing this work on a branch.  It's a big task, and has potential to mess up other features.

**Comment by JoyJing1** [comment]
- MVP - feature bullet points customized
- Styling incorporated into each stage
- Updated timeline & re-split phases
- Newsfeed branching - duly noted

**Comment by JoyJing1** [comment]
- MVP - feature bullet points customized
- Styling incorporated into each stage
- Updated timeline & re-split phases
- Newsfeed branching - duly noted
