### ISSUE TITLE
DB Schema

### ISSUE THREAD

**Issue by claire-kz** [JoyJing1/Friendex#5]
- table naming convention is camel_case 
- **Don't have a separate table for friend requests.**  Add a column to the friendships table that tracks the status.  Every row of the friendships table will be either 'approved', 'pending', or 'not approved'. 
- What is a post `receiver_id`?
- What is the `ads` table?  Haven't seen this anywhere else in the project proposal.
- In bonus, messages probably needs a text field column

**Comment by JoyJing1** [comment]
Post receiver_id -- the id of the user whose profile the post is made on. What do people usually label it?
